name: Daily Churn Prediction

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows you to run it manually from the UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install numpy pandas matplotlib seaborn scikit-learn python-dotenv xgboost imbalanced-learn shap interpret gspread gspread-dataframe google-auth psycopg2-binary
  

    - name: Run Prediction Script
      env:
        # Map your GitHub Secrets to Environment Variables
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_PORT: ${{ secrets.DB_PORT }}
        GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
      run: python predict.py
